//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyTTTAEntities3 : DbContext
    {
        public QuanLyTTTAEntities3()
            : base("name=QuanLyTTTAEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GiaoVien> GiaoViens { get; set; }
        public virtual DbSet<InClass> InClasses { get; set; }
        public virtual DbSet<InStudent> InStudents { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<UserAD> UserADs { get; set; }
        public virtual DbSet<UserSV> UserSVs { get; set; }
        public virtual DbSet<NopHP> NopHPs { get; set; }
    }
}
