//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class InStudent
    {
        public InStudent()
        {
            this.UserSVs = new HashSet<UserSV>();
        }
    
        public int IDHV { get; set; }
        public string HT { get; set; }
        public string SDT { get; set; }
        public string DC { get; set; }
        public Nullable<System.DateTime> NDKH { get; set; }
        public Nullable<bool> TTHP { get; set; }
        public string MaLop { get; set; }
        public string EMAIL { get; set; }
    
        public virtual InClass InClass { get; set; }
        public virtual ICollection<UserSV> UserSVs { get; set; }
        public virtual NopHP NopHP { get; set; }
    }
}
