//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSV
    {
        public int IDHV { get; set; }
        public string TaiKhoanSV { get; set; }
        public string MatKhauSV { get; set; }
    
        public virtual InStudent InStudent { get; set; }
    }
}
