//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAD
    {
        public int IDAD { get; set; }
        public string TaiKhoanAD { get; set; }
        public string MatKhauAD { get; set; }
    }
}
